// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhufzNoO_Wio9UKG3hLmYg0jf1WgXWbI',
    appId: '1:1060914117311:web:b40d2f1a1d15acaa25a40a',
    messagingSenderId: '1060914117311',
    projectId: 'instagram-clone-27ab4',
    authDomain: 'instagram-clone-27ab4.firebaseapp.com',
    storageBucket: 'instagram-clone-27ab4.firebasestorage.app',
    measurementId: 'G-YH4CK0R4RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vjEvjy-dUYlO0s5YlSaH6s74d0aeqMI',
    appId: '1:1060914117311:android:607b9e8a3ba0a35925a40a',
    messagingSenderId: '1060914117311',
    projectId: 'instagram-clone-27ab4',
    storageBucket: 'instagram-clone-27ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRd7KTEz8N1P_0vH78iCqMcbg0CRVPpg',
    appId: '1:1060914117311:ios:b1cc9213af8e82fe25a40a',
    messagingSenderId: '1060914117311',
    projectId: 'instagram-clone-27ab4',
    storageBucket: 'instagram-clone-27ab4.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBRd7KTEz8N1P_0vH78iCqMcbg0CRVPpg',
    appId: '1:1060914117311:ios:b1cc9213af8e82fe25a40a',
    messagingSenderId: '1060914117311',
    projectId: 'instagram-clone-27ab4',
    storageBucket: 'instagram-clone-27ab4.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIhufzNoO_Wio9UKG3hLmYg0jf1WgXWbI',
    appId: '1:1060914117311:web:4ffbbf2c51e5ade825a40a',
    messagingSenderId: '1060914117311',
    projectId: 'instagram-clone-27ab4',
    authDomain: 'instagram-clone-27ab4.firebaseapp.com',
    storageBucket: 'instagram-clone-27ab4.firebasestorage.app',
    measurementId: 'G-QKP8NE6HD5',
  );
}
